# This workflow tests that Slack is properly notified
name: Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Slack notification success
      if: success()
      uses: emmasax4/notify-slack-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: '#general'
        color: '#00FFAA'
        username: 'github'
        icon_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        image_url: 'https://storage.googleapis.com/slack-images-cyclops/ci/It_Compiles_Ship_It.png'

    - name: Slack notification failure
      if: failure()
      uses: emmasax4/notify-slack-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: '#general'
        color: '#CC0000'
        username: 'github'
        icon_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        image_url: 'https://media.giphy.com/media/njYrp176NQsHS/giphy.gif'
